# Generated by Django 4.2.1 on 2023-05-14 15:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Title')),
                ('description', models.TextField(max_length=300, verbose_name='Description')),
                ('description_en', models.TextField(max_length=300, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(max_length=300, null=True, verbose_name='Description')),
                ('price_one_delivery', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Price for one delivery')),
            ],
            options={
                'verbose_name': 'Delivery vendor',
                'verbose_name_plural': 'Delivery vendors',
            },
        ),
        migrations.CreateModel(
            name='DeliverySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time_start_weekday', models.TimeField(choices=[(datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00')], default=datetime.time(10, 0), verbose_name='Delivery time start on weekday')),
                ('delivery_time_end_weekday', models.TimeField(choices=[(datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00')], default=datetime.time(11, 0), verbose_name='Delivery time end on weekday')),
                ('delivery_time_start_weekend', models.TimeField(choices=[(datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00')], default=datetime.time(10, 0), verbose_name='Delivery time start on weekend')),
                ('delivery_time_end_weekend', models.TimeField(choices=[(datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00')], default=datetime.time(11, 0), verbose_name='Delivery time end on weekend')),
                ('everyday_same_time', models.BooleanField(choices=[(True, 'Everyday at the same time'), (False, 'Weekdays and weekends')], default=False, verbose_name='Mode')),
                ('delivery_vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.deliveryvendor', verbose_name='Delivery vendor')),
            ],
            options={
                'verbose_name': 'Delivery schedule',
                'verbose_name_plural': 'Delivery schedules',
            },
        ),
    ]
