# Generated by Django 4.2.1 on 2023-05-14 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='Title')),
                ('title_en', models.CharField(default='', max_length=30, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(default='', max_length=30, null=True, verbose_name='Title')),
                ('description', models.TextField(default='', max_length=1000, verbose_name='Description')),
                ('description_en', models.TextField(default='', max_length=1000, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(default='', max_length=1000, null=True, verbose_name='Description')),
                ('slug', models.SlugField(blank=True, default='', max_length=30, null=True, unique=True)),
                ('slug_en', models.SlugField(blank=True, default='', max_length=30, null=True, unique=True)),
                ('slug_ru', models.SlugField(blank=True, default='', max_length=30, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='DailyMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Title')),
                ('title_en', models.CharField(default='', max_length=100, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(default='', max_length=100, null=True, verbose_name='Title')),
                ('calories', models.PositiveIntegerField(default=0, verbose_name='Calories')),
            ],
            options={
                'verbose_name': 'Daily meal',
                'verbose_name_plural': 'Daily meals',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=60, verbose_name='Title')),
                ('title_en', models.CharField(default='', max_length=60, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(default='', max_length=60, null=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=60, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/photos/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('title_en', models.CharField(max_length=30, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=30, null=True, verbose_name='Title')),
                ('description', models.TextField(default='', max_length=1000, verbose_name='Description')),
                ('description_en', models.TextField(default='', max_length=1000, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(default='', max_length=1000, null=True, verbose_name='Description')),
                ('calories_daily', models.PositiveIntegerField(default=0, verbose_name='Calories average')),
                ('slug', models.SlugField(blank=True, default='', max_length=30, null=True, unique=True)),
                ('slug_en', models.SlugField(blank=True, default='', max_length=30, null=True, unique=True)),
                ('slug_ru', models.SlugField(blank=True, default='', max_length=30, null=True, unique=True)),
                ('price_auto', models.BooleanField(default=True, verbose_name='Auto price')),
                ('price_daily', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Daily costs')),
                ('price_weekly', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Weekly costs')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monthly costs')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.category', verbose_name='Category')),
                ('day_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monday', to='menu.dailymeal', verbose_name='Monday')),
                ('day_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuesday', to='menu.dailymeal', verbose_name='Tuesday')),
                ('day_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wednesday', to='menu.dailymeal', verbose_name='Wednesday')),
                ('day_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thursday', to='menu.dailymeal', verbose_name='Thursday')),
                ('day_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friday', to='menu.dailymeal', verbose_name='Friday')),
                ('day_6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saturday', to='menu.dailymeal', verbose_name='Saturday')),
                ('day_7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sunday', to='menu.dailymeal', verbose_name='Sunday')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.photo', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=60, verbose_name='Title')),
                ('title_en', models.CharField(default='', max_length=60, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(default='', max_length=60, null=True, verbose_name='Title')),
                ('description', models.TextField(default='', max_length=1000, verbose_name='Description')),
                ('description_en', models.TextField(default='', max_length=1000, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(default='', max_length=1000, null=True, verbose_name='Description')),
                ('calories', models.PositiveIntegerField(default=0, verbose_name='Calories')),
                ('meal_of_the_day', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Meal of the day')),
                ('slug', models.SlugField(blank=True, default='', max_length=60, null=True, unique=True)),
                ('slug_en', models.SlugField(blank=True, default='', max_length=60, null=True, unique=True)),
                ('slug_ru', models.SlugField(blank=True, default='', max_length=60, null=True, unique=True)),
                ('ingredients', models.ManyToManyField(related_name='dishes', to='menu.ingredient', verbose_name='Ingredients')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.photo', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Dish',
                'verbose_name_plural': 'Dishes',
            },
        ),
        migrations.AddField(
            model_name='dailymeal',
            name='dish_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakfast', to='menu.dish', verbose_name='Breakfast'),
        ),
        migrations.AddField(
            model_name='dailymeal',
            name='dish_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brunch', to='menu.dish', verbose_name='Brunch'),
        ),
        migrations.AddField(
            model_name='dailymeal',
            name='dish_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lunch', to='menu.dish', verbose_name='Lunch'),
        ),
        migrations.AddField(
            model_name='dailymeal',
            name='dish_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dinner', to='menu.dish', verbose_name='Dinner'),
        ),
        migrations.AddField(
            model_name='dailymeal',
            name='dish_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supper', to='menu.dish', verbose_name='Supper'),
        ),
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.photo', verbose_name='Photo'),
        ),
    ]
